generate_task:
  timeout_in: 120m
  compute_engine_instance:
    image_project: cirrus-images
    image: family/docker-builder
    platform: linux
    cpu: 8
    memory: 16G

  gnuzilla_cache:
    folder: gnu-icecat-build-script/result
    fingerprint_key: gnuzilla-soure
    populate_script: 
      - pwd
      - git submodule update --init --recursive
      - ls
      - cd ./gnu-icecat-build-script
      - docker build . -t vbramselaar/icecat-builder
      - mkdir -p result
      - docker run --rm -e stage=generate -v $(pwd)/result:/root/result vbramselaar/icecat-builder

build_task:
  timeout_in: 120m
  depends_on:
    - generate_task
  compute_engine_instance:
    image_project: cirrus-images
    image: family/docker-builder
    platform: linux
    cpu: 8
    memory: 16G
    
  gnuzilla_cache:
    folder: gnu-icecat-build-script/result
    fingerprint_key: gnuzilla-soure

  build_script:
    - pwd
    - ls
    - cd ./gnu-icecat-build-script
    - docker build . -t vbramselaar/icecat-builder
    - mkdir -p result
    - docker run --rm -e stage=build -v $(pwd)/result:/root/result vbramselaar/icecat-builder
