compute_engine_instance:
  image_project: cirrus-images
  image: family/docker-builder
  platform: linux
  cpu: 8
  memory: 16G

gnuzilla_cache:
  folder: result
  fingerprint_key: gnuzilla-source
  populate_script: mkdir result

generate_task:
  timeout_in: 120m
  generate_script:
    - pwd
    - git submodule update --init --recursive
    - ls
    - docker build gnu-icecat-build-script -t vbramselaar/icecat-builder
    - docker run --rm -e stage=generate -v $(pwd)/result:/root/result vbramselaar/icecat-builder

build_task:
  timeout_in: 120m
  depends_on:
    - generate
  build_script:
    - pwd
    - git submodule update --init --recursive
    - ls
    - docker build gnu-icecat-build-script -t vbramselaar/icecat-builder
    - docker run --rm -e stage=build -v $(pwd)/result:/root/result vbramselaar/icecat-builder
