container:
  dockerfile: Dockerfile
  cpu: 8
  memory: 16G

env:
  CIRRUS_CLONE_SUBMODULES: true

generate_task:
  timeout_in: 120m
  container:
    dockerfile: gnu-icecat-build-script/Dockerfile
    docker_arguments:
      stage: generate
    cpu: 8
    memory: 16G
  result_cache:
    folder: result
    fingerprint_key: gnuzilla
    populate_script:
      - mkdir -p result
  artifacts:
    name: Gnuzilla source
    path: "result/*.tar.bz2"

build_task:
  timeout_in: 120m
  container:
    dockerfile: gnu-icecat-build-script/Dockerfile
    docker_arguments:
      stage: build
    cpu: 8
    memory: 16G
  depends_on:
    - generate
  result_cache:
    folder: result
    fingerprint_key: gnuzilla
  artifacts:
    name: Icecat build
    path: "result/icecat"
