task:
  compute_engine_instance:
    image_project: cirrus-images
    image: family/docker-builder
    platform: linux
    cpu: 4
    memory: 16G
    timeout_in: 120m

  build_script:
    - cd ./gnu-icecat-build-script
    - docker build . -t vbramselaar/icecat-builder
    - mkdir -p result
    - docker run -it --rm -v $(pwd)/result:/home/builder/result vbramselaar/icecat-builder
