compute_engine_instance:
  image_project: cirrus-images
  image: family/docker-builder
  platform: linux
  cpu: 8
  memory: 16G

env:
  CIRRUS_CLONE_SUBMODULES: true

docker_builder:
  build_script: docker build gnu-icecat-build-script -t vbramselaar/icecat-builder

generate_task:
  timeout_in: 120m
  result_cache:
    folder: result
    fingerprint_key: gnuzilla
    populate_script:
      - mkdir -p result
  generate_script:
    - pwd
    - ls
    - docker run --rm -e stage=generate -v $(pwd)/result:/root/result vbramselaar/icecat-builder
  binaries_artifacts:
    path: "result/*.tar.bz2"

build_task:
  timeout_in: 120m
  result_cache:
    folder: result
    fingerprint_key: gnuzilla
  depends_on:
    - generate
  build_script:
    - pwd
    - ls
    - docker run --rm -e stage=build -v $(pwd)/result:/root/result vbramselaar/icecat-builder
