compute_engine_instance:
  image_project: cirrus-images
  image: family/docker-builder
  platform: linux
  cpu: 8
  memory: 16G

env:
  CIRRUS_CLONE_SUBMODULES: true

generate_task:
  timeout_in: 120m
  result_cache:
    folder: result
    fingerprint_key: gnuzilla
    populate_script:
      - mkdir -p result
  generate_script:
    - pwd
    - ls
    - docker build gnu-icecat-build-script -t vbramselaar/icecat-builder
    - docker run --rm -e stage=generate -v $(pwd)/result:/root/result vbramselaar/icecat-builder
  gnuzilla_source_artifacts:
    path: "result/*.tar.bz2"

build_task:
  timeout_in: 120m
  depends_on:
    - generate
  result_cache:
    folder: result
    fingerprint_key: gnuzilla
  build_script:
    - pwd
    - ls result
    - docker build gnu-icecat-build-script -t vbramselaar/icecat-builder
    - docker run --rm -e stage=build -v $(pwd)/result:/root/result vbramselaar/icecat-builder
  icecat_build_artifacts:
    path: "result/icecat"
